// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/game-stat": {
            "post": {
                "description": "Log the statistics of a player in a game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Log game statistics",
                "parameters": [
                    {
                        "description": "GameStat",
                        "name": "stat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.GameStat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game stat logged successfully!",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game-stats": {
            "get": {
                "description": "Get the list of game statistics",
                "produces": [
                    "application/json"
                ],
                "summary": "List game statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.GameStat"
                            }
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "description": "Get the list of players",
                "produces": [
                    "application/json"
                ],
                "summary": "List players",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Player"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.GameStat": {
            "type": "object",
            "properties": {
                "assists": {
                    "type": "integer"
                },
                "blocks": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "fouls": {
                    "type": "integer"
                },
                "minutes_played": {
                    "type": "number"
                },
                "player_id": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "rebounds": {
                    "type": "integer"
                },
                "steals": {
                    "type": "integer"
                },
                "turnovers": {
                    "type": "integer"
                }
            }
        },
        "main.Player": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "team": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NBA Stats API",
	Description:      "This is a sample server for logging NBA player statistics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
