definitions:
  models.GameStat:
    properties:
      assists:
        type: integer
      blocks:
        type: integer
      fouls:
        type: integer
      game_date:
        type: string
      minutes_played:
        type: number
      player_id:
        type: integer
      points:
        type: integer
      rebounds:
        type: integer
      steals:
        type: integer
      turnovers:
        type: integer
    type: object
  models.Player:
    properties:
      id:
        type: integer
      name:
        type: string
      team_id:
        description: New field for foreign key
        type: integer
    type: object
info:
  contact: {}
paths:
  /add-players:
    post:
      consumes:
      - application/json
      description: Add a new player to the database
      parameters:
      - description: Player
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/models.Player'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Player'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add a new player
      tags:
      - players
  /add-stat:
    post:
      consumes:
      - application/json
      description: Add a new game stat to the database
      parameters:
      - description: Game Stat
        in: body
        name: stat
        required: true
        schema:
          $ref: '#/definitions/models.GameStat'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.GameStat'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add a new game stat
      tags:
      - stats
  /players:
    get:
      description: Get a list of all players
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Player'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: player stats
      tags:
      - players
swagger: "2.0"
