basePath: /
definitions:
  main.GameStat:
    properties:
      assists:
        type: integer
      blocks:
        type: integer
      date:
        type: string
      fouls:
        type: integer
      minutes_played:
        type: number
      player_id:
        type: integer
      points:
        type: integer
      rebounds:
        type: integer
      steals:
        type: integer
      turnovers:
        type: integer
    type: object
  main.Player:
    properties:
      id:
        type: integer
      name:
        type: string
      team:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: This is a sample server for logging NBA player statistics.
  title: NBA Stats API
  version: "0.1"
paths:
  /game-stat:
    post:
      consumes:
      - application/json
      description: Log the statistics of a player in a game
      parameters:
      - description: GameStat
        in: body
        name: stat
        required: true
        schema:
          $ref: '#/definitions/main.GameStat'
      produces:
      - application/json
      responses:
        "200":
          description: Game stat logged successfully!
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Log game statistics
  /game-stats:
    get:
      description: Get the list of game statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.GameStat'
            type: array
      summary: List game statistics
  /players:
    get:
      description: Get the list of players
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Player'
            type: array
      summary: List players
swagger: "2.0"
